from server.lifespans.chat_model import chat_model as chat_model
from server.lifespans.create_redis_index import create_redis_index as create_redis_index
from server.lifespans.download_embeddings import download_embeddings as download_embeddings
from server.lifespans.download_nltk import download_nltk as download_nltk
