services:
  backend:
    container_name: backend
    init: true
    environment:
      REDIS_URL: redis://redis:6379
      BACKEND_PORT: ${BACKEND_PORT}
      USE_CUDA: True
    shm_size: 1G
    ulimits:
      stack: 67108864
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./tmp/backend/huggingface:/home/user/.cache/huggingface/hub
      - ./tmp/backend/torch:/home/user/.cache/torch
      - ./tmp/backend/nltk:/home/user/.cache/nltk
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
