services:
  postgres:
    container_name: postgres
    image: tensorchord/vchord-suite:pg18-latest
    init: true
    ports: [5432:5432]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/postgres:/var/lib/postgresql
      - ./server/database/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 50

  migrations:
    container_name: migrations
    init: true
    command:
      - sh
      - -c
      - |
        litestar --app-dir .venv/lib/python3.13/site-packages --app src.app:app database upgrade --no-prompt
        litestar --app-dir .venv/lib/python3.13/site-packages --app src.app:app database make-migrations --no-prompt
        litestar --app-dir .venv/lib/python3.13/site-packages --app src.app:app database upgrade --no-prompt
    environment:
      POSTGRES_ENDPOINT: postgres:5432
    build:
      context: .
      dockerfile: Dockerfile
    volumes: [./server/migrations:/home/user/migrations]
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    container_name: backend
    init: true
    ports: [7860:7860]
    environment:
      SERVER_PORT: 7860
      CT2_USE_EXPERIMENTAL_PACKED_GEMM: 1
      OMP_NUM_THREADS: 2
      CHAT_MODEL_THREADS: 3
    security_opt: [seccomp:unconfined]
    shm_size: 8G
    ulimits:
      stack: 67108864
      memlock:
        soft: -1
        hard: -1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tmp/server/huggingface:/home/user/.cache/huggingface/hub
    depends_on:
      migrations:
        condition: service_completed_successfully
