services:
  backend:
    container_name: backend
    init: true
    ports: [7860:7860]
    environment:
      SERVER_PORT: 7860
      CHAT_MODEL_THREADS: 3
      USE_CUDA: True
    shm_size: 8G
    ulimits:
      stack: 67108864
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./tmp/server/huggingface:/home/user/.cache/huggingface/hub
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
