network:
  host: 0.0.0.0
  disable_auth: true
  allowed_origins: []

model:
  model_name: Qwen3.8-27B-exl3-SC_4.00bpw_H5
  max_seq_len: 16384
  cache_size: 16384
  cache_mode: Q8
  chunk_size: 2048
  output_chunking: true
  max_batch_size: 1
  vision: false
  template_vars_default:
    enable_thinking: false
    preserve_thinking: false
  template_vars_force:
    enable_thinking: false
  reasoning: false
  tool_format: qwen3_5

draft_model:
  draft_mode: mtp
  draft_cache_mode: Q8
  draft_num_tokens: 4

sampling:
  override_preset: reliable

memory:
  sysmem_recurrent_cache: 2048
  sysmem_kv_cache: 0
  cuda_malloc_async: false
