FROM caddy:builder-alpine as builder

RUN xcaddy build --with github.com/caddyserver/cache-handler


FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

ENTRYPOINT ["/bin/sh", "-c"]
